variable eventhub_namespace {}
variable client_config   {}   
variable resource_group_name {}
variable location {}
variable global_settings {}
variable settings {}
variable base_tags {}
variable diagnostics {}
variable subscription_id  {}