variable global_settings {}
variable client_config {}
variable settings {}
variable resource_group_name {}
variable location {}
variable keyvault_id {}
variable storage_accounts {}
variable azuread_groups {}
variable vnets {}
variable private_endpoints {}
variable resource_groups {}
variable base_tags {}
