variable global_settings {}
variable client_config {}
variable settings {}
variable resource_groups {}
variable private_endpoints {}
variable private_dns {}
variable remote_objects {}
variable vnet {}
variable base_tags {}