
resource "azuread_user" "use" {
  user_principal_name         = var.settings.user_principal_name
  display_name                = var.settings.display_name
  account_enabled             = try(var.settings.account_enabled, null)
  age_group                   = try(var.settings.age_group, null)
  business_phones             = try(var.settings.business_phones, null)
  city                        = try(var.settings.city, null)
  company_name                = try(var.settings.company_name, null)
  consent_provided_for_minor  = try(var.settings.consent_provided_for_minor, null)
  cost_center                 = try(var.settings.cost_center, null)
  country                     = try(var.settings.country, null)
  department                  = try(var.settings.department, null)
  division                    = try(var.settings.division, null)
  employee_id                 = try(var.settings.employee_id, null)
  employee_type               = try(var.settings.employee_type, null)
  force_password_change       = try(var.settings.force_password_change, null)
  given_name                  = try(var.settings.given_name, null)
  fax_number                  = try(var.settings.fax_number, null)
  job_title                   = try(var.settings.job_title, null)
  mail                        = try(var.settings.mail, null)
  mail_nickname               = try(var.settings.mail_nickname, null)
  manager_id                  = try(var.settings.manager_id, null)
  mobile_phone                = try(var.settings.mobile_phone, null)
  office_location             = try(var.settings.office_location, null)
  onpremises_immutable_id     = try(var.settings.onpremises_immutable_id, null)
  other_mails                 = try(var.settings.other_mails, null)
  password                    = try(var.settings.password, null)
  disable_strong_password     = try(var.settings.disable_strong_password, null)
  disable_password_expiration = try(var.settings.disable_password_expiration, null)
  postal_code                 = try(var.settings.postal_code, null)
  preferred_language          = try(var.settings.preferred_language, null)
  show_in_address_list        = try(var.settings.show_in_address_list, null)
  state                       = try(var.settings.state, null)
  street_address              = try(var.settings.street_address, null)
  surname                     = try(var.settings.surname, null)
  usage_location              = try(var.settings.usage_location, null)
}
