#
# Copyright (c) Microsoft Corporation
# Licensed under the MIT License.
#

name: PR Tflint

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  TF_VERSION: "1.8.4"
  TF_LINT_VERSION: "v0.50.3"

jobs:
  linting:
    name: Format and Lint Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version:  ${{ env.TF_VERSION }}

      - name: Install Terraform Linter
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: ${{ env.TF_LINT_VERSION }}

      - name: Run TFLint with reviewdog
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: info
          tflint_init: true
